[package]
authors = ["Kiran Shila <me@kiranshila.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "syntax"
version = "0.1.0"

[dependencies]
lexer = {path = "../lexer"}
num-derive = "0.3"
num-traits = "0.2"
rowan = "0.15"